#!/bin/bash
#PBS -N BlastScript_1
#PBS -l nodes=1     #think about this
#PBS -m abe
#PBS -M cmmcbride@haverford.edu
#PBS -e BlastScript_1_Notices
#PBS -o BlastScript_1_Notices

# BLAST query genes against nucleotide databases. 

tblastn -task tblastn -db /data/db/[WHATEVER YOU NAME THIS] -query [QuerySequences?] -evalue 1 -outfmt "6 sseqid qstart qend sstart send pident evalue" -max_target_seqs [inserthere] -out Blast_1_Data

# qacc: Query accession
# sseqid: Query Seq-id
# sgi: Subject GI
# sacc: Subject Accession
# qstart: Start of Alignment in Query
# qend: End of Alignment in Query
# sstart: Start of Alignment in Subject
# send: End of Alignment in Query
# qseq: Aligned Part of Query Sequence
# sseq: Aligned Part of Subject Sequence
# evalue: Expect value
# length: Alignment Length
# pident: Percentage of Identical Matches
# nident: number of Identical Matches
# staxids: unique Subject Taxonomy ID(s)
# sscinames: unique Subject Scientific Name(s)
# scomnames: unique Subject Common Name(s)
# sblastnames: unique Subject Blast Name(s)
# sskingdoms: unique Subject Super Kingdom(s)
# stitle: Subject Title
# sstrand: Subject Strand


